spring:
  boot:
    admin:
      client:
        url: http://localhost:1111/
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: Axis#123
    url: jdbc:mysql://localhost:3306/ecommerce?autoReconnect=true&useSSL=false
    username: root

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    
management:
  endpoints:
    web:
      exposure:
        include: '*'

server:
 port: 8081

# Application messages goes here
auth-service:
 messages: 
  userReg: User Created
  userRegErr: User Creation Failed
  login: Login Success
  loginErr: Invalid Credentials  
